<!DOCTYPE html>

<html>

<style> h1 {text-align: center;} </style>
<style> h2 {text-align: center;}</style>

<style>
.mycontainer{
    width: 100%;
    overflow: auto;
}

.mycontainer div{
    width: 33%;
    float: left;
}

</style>


<head>

    <meta charset="utf-8">
    &lt;meta name = "viewport" content = "width=device", initial-scale = 1&gt;

    <title>
        Sris Projects
    </title>
<b>  </b>

</head>
 
<h1 style="color:#000000"> Who is sri? </h1>
<h2> Summary </h2>

<p>
   I am an enthusiastic and motivated Electrical Engineering student with a strong foundation in both hardware and software an example is this website your reading right now built from scratch using HTML , CSS, and javascript. 
   complemented by proficiency in programming languages such as C, Python, and Java. 
   My background includes certification in game development through Byju’s, where I learned to integrate creativity with technical problem-solving, further broadening my engineering perspective. 
   I bring hands-on experience in circuit design, system analysis, and practical implementation of control and power systems through my active involvement with TMU’s MACH initiative and the TMAV team. 
   These experiences have not only sharpened my technical skills but also strengthened my ability to work in interdisciplinary teams, manage complex projects, and apply engineering principles to solve real-world challenges. 
   I am deeply passionate about innovation and dedicated to leveraging my technical expertise to design efficient, impactful, and forward-looking engineering solutions that contribute meaningfully to advancing technology and improving systems.



</p>

<a href="https://www.linkedin.com/in/sri-damarla-88439122b/"> here is My Linkedin!</a>

<hr>

<h3 style="background-color:burlywood"> Project 1: Led Lights with Micro-controller </h3>

<h4 style="background-color:burlywood"> Schmatic </h4>

<body style="background-color:beige">


   


    <div>

         <img src="Images/Screenshot 2025-08-01 172440.png" style="width:500.0px;height:350.0px" border="5">
        <h5 style="font-size:large"> Understanding : </h5>
    
        <p style="font-size:medium">
        In the image above , that is my  Kicad 9.0  Schematic for an LED light conencted from a course, the Led light is 
        controlled with an Microcontroller in this case it was a  ESP8266 , conencting the ressistors into the right GPIO pins
        was crucial, i also had to work with MOSFETS in order for lighting to be controlled properly such as dimming and showing multiple Colours

    </p>

</div>

<div>
   <h4 style="font-size:large"> parts for use : </h4>
   
    <img src="Images/Screenshot 2025-08-26 174603.png" style="width:500.0px;height:350.0px" border="5">

    <p style="font-size:medium">
        this <a href="https://docs.google.com/document/d/1TrZ-8XsBQPAhL9ruoeXO6IJz6R90cu6L-phbHu_lxyE/edit?usp=sharing"> document</a> shows the specfic parts i used to build this LED in the schematic, the obvouis parts
        arent shown *wires etc* 
    </p>


</div>


    

</body>

</html>

